In [2]:
import numpy as np
import pandas as pd

Different ways of creating Pandas
1. From a list
2. from Numpy Array
3. from a dictionary

In [8]:
#from a list
data = [10,20,30,40,50]
s_list = pd.Series(data)
print(s_list)
print(s_list[1])

0    10
1    20
2    30
3    40
4    50
dtype: int64
20

In [7]:
#from a Numpy array
data_array = np.array([10, 20, 30, 40, 50])
s_arr = pd.Series(data_array)
print(s_arr)
print(s_arr[1])

0    10
1    20
2    30
3    40
4    50
dtype: int32
20

In [13]:
#from adictionary
data_dict = {'A': 10,'B': 20,'C': 30,'D': 40,'E': 50}
s_dict = pd.Series(data_dict)
print("Full Series:")
print(s_dict)

Full Series:
A    10
B    20
C    30
D    40
E    50
dtype: int64

In [14]:
# Print individual values
print("\nIndividual values:")
for key, value in data_dict.items():
    print(f"Key: {key}, Value: {value}")

Individual values:
Key: A, Value: 10
Key: B, Value: 20
Key: C, Value: 30
Key: D, Value: 40
Key: E, Value: 50

In [15]:
# Access a single value by key (using [] instead of {})
print("\nAccess value for key 'A':", s_dict['A'])

Access value for key 'A': 10

In [16]:
# Access a single value by key (using [] instead of {})
print("\nAccess value for all the keys :", s_dict['A'], s_dict['B'], s_dict['C'], s_dict['D'], s_dict['E'])

Access value for all the keys : 10 20 30 40 50

Operations onPandas Series
1. Indexing and slicing
2. Mean and Max functions
3. Sorting
4. Unique values

Dataframe
Dataframes can be created from :
1. List
2. Dictinary
3. CSV file

In [28]:
#1. Dataframe created from a list
#creating a list of lists
data = [[1, 'John', 25],
        [2, 'Alice', 30],
        [3, 'Bob', 45]]

#Creating a Dataframe from the List
df = pd.DataFrame(data, columns=['ID', 'Name', 'Age'])

print(df)

   ID   Name  Age
0   1   John   25
1   2  Alice   30
2   3    Bob   45

In [29]:
# Append new row to the list
data.append([5, 'Julius', 38])

print(df)

   ID   Name  Age
0   1   John   25
1   2  Alice   30
2   3    Bob   45

In [30]:
# Append new row to the list
data.append([4, 'Diana', 28])

# Create DataFrame from updated list
df = pd.DataFrame(data, columns=['ID', 'Name', 'Age'])

print(df)

   ID    Name  Age
0   1    John   25
1   2   Alice   30
2   3     Bob   45
3   5  Julius   38
4   4   Diana   28

In [25]:
print(data)

[[1, 'John', 25], [2, 'Alice', 30], [3, 'Bob', 45]]

In [23]:
# Remove the second row (index 1 → Alice)
data.pop(1)

print(data)

[[1, 'John', 25], [4, 'Diana', 28], [5, 'Julius', 38], [4, 'Diana', 28]]

In [31]:
# Remove Bob’s record directly
data.remove([3, 'Bob', 45])

print(data)

[[1, 'John', 25], [2, 'Alice', 30], [5, 'Julius', 38], [4, 'Diana', 28]]

PANDAS AND EXCEL DATASET - dataframe operations

In [33]:
df = pd.read_csv('Telco-Churn.csv')
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [37]:

# Print the last 5 rows (default)
print(df.tail())

# Print the last 10 rows (optional)
print(df.tail(10))

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
7038    No
7039    No
7040    No
7041   Yes
7042    No

[5 rows x 21 columns]
      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
7033  9767-FFLEM    Male              0      No         No      38
7034  0639-TSIQW  Female              0      No         No      67
7035  8456-QDAVC    Male              0      No         No      19
7036  7750-EYXWZ  Female              0      No         No      12
7037  2569-WGERO  Female              0      No         No      72
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
7033          Yes                No     Fiber optic                   No  ...
7034          Yes               Yes     Fiber optic                  Yes  ...
7035          Yes                No     Fiber optic                   No  ...
7036           No  No phone service             DSL                   No  ...
7037          Yes                No              No  No internet service  ...
7038          Yes               Yes             DSL                  Yes  ...
7039          Yes               Yes     Fiber optic                   No  ...
7040           No  No phone service             DSL                  Yes  ...
7041          Yes               Yes     Fiber optic                   No  ...
7042          Yes                No     Fiber optic                  Yes  ...

         DeviceProtection          TechSupport          StreamingTV  \
7033                   No                   No                   No
7034                  Yes                   No                  Yes
7035                   No                   No                  Yes
7036                  Yes                  Yes                  Yes
7037  No internet service  No internet service  No internet service
7038                  Yes                  Yes                  Yes
7039                  Yes                   No                  Yes
7040                   No                   No                   No
7041                   No                   No                   No
7042                  Yes                  Yes                  Yes

          StreamingMovies        Contract PaperlessBilling  \
7033                   No  Month-to-month              Yes
7034                   No  Month-to-month              Yes
7035                   No  Month-to-month              Yes
7036                  Yes        One year               No
7037  No internet service        Two year              Yes
7038                  Yes        One year              Yes
7039                  Yes        One year              Yes
7040                   No  Month-to-month              Yes
7041                   No  Month-to-month              Yes
7042                  Yes        Two year              Yes

                  PaymentMethod MonthlyCharges  TotalCharges Churn
7033    Credit card (automatic)          69.50       2625.25    No
7034    Credit card (automatic)         102.95       6886.25   Yes
7035  Bank transfer (automatic)          78.70        1495.1    No
7036           Electronic check          60.65         743.3    No
7037  Bank transfer (automatic)          21.15        1419.4    No
7038               Mailed check          84.80        1990.5    No
7039    Credit card (automatic)         103.20        7362.9    No
7040           Electronic check          29.60        346.45    No
7041               Mailed check          74.40         306.6   Yes
7042  Bank transfer (automatic)         105.65        6844.5    No

[10 rows x 21 columns]

In [38]:
# Print the frst 5 rows (default)
print(df.head())

# Print the last 10 rows (optional)
print(df.head(10))

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No
1                No             DSL            Yes  ...              Yes
2                No             DSL            Yes  ...               No
3  No phone service             DSL            Yes  ...              Yes
4                No     Fiber optic             No  ...               No

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes
1          No          No              No        One year               No
2          No          No              No  Month-to-month              Yes
3         Yes          No              No        One year               No
4          No          No              No  Month-to-month              Yes

               PaymentMethod MonthlyCharges  TotalCharges Churn
0           Electronic check          29.85         29.85    No
1               Mailed check          56.95        1889.5    No
2               Mailed check          53.85        108.15   Yes
3  Bank transfer (automatic)          42.30       1840.75    No
4           Electronic check          70.70        151.65   Yes

[5 rows x 21 columns]
   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes
5  9305-CDSKC  Female              0      No         No       8          Yes
6  1452-KIOVK    Male              0      No        Yes      22          Yes
7  6713-OKOMC  Female              0      No         No      10           No
8  7892-POOKP  Female              0     Yes         No      28          Yes
9  6388-TABGU    Male              0      No        Yes      62          Yes

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No
1                No             DSL            Yes  ...              Yes
2                No             DSL            Yes  ...               No
3  No phone service             DSL            Yes  ...              Yes
4                No     Fiber optic             No  ...               No
5               Yes     Fiber optic             No  ...              Yes
6               Yes     Fiber optic             No  ...               No
7  No phone service             DSL            Yes  ...               No
8               Yes     Fiber optic             No  ...              Yes
9                No             DSL            Yes  ...               No

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes
1          No          No              No        One year               No
2          No          No              No  Month-to-month              Yes
3         Yes          No              No        One year               No
4          No          No              No  Month-to-month              Yes
5          No         Yes             Yes  Month-to-month              Yes
6          No         Yes              No  Month-to-month              Yes
7          No          No              No  Month-to-month               No
8         Yes         Yes             Yes  Month-to-month              Yes
9          No          No              No        One year               No

               PaymentMethod MonthlyCharges  TotalCharges Churn
0           Electronic check          29.85         29.85    No
1               Mailed check          56.95        1889.5    No
2               Mailed check          53.85        108.15   Yes
3  Bank transfer (automatic)          42.30       1840.75    No
4           Electronic check          70.70        151.65   Yes
5           Electronic check          99.65         820.5   Yes
6    Credit card (automatic)          89.10        1949.4    No
7               Mailed check          29.75         301.9    No
8           Electronic check         104.80       3046.05   Yes
9  Bank transfer (automatic)          56.15       3487.95    No

[10 rows x 21 columns]

In [40]:
#Descrie the dataset
print(df.describe())

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [42]:
#shape function dislays the rows and columns in the dataset
print("\n The shape of the dataset")
df.shape

 The shape of the dataset

(7043, 21)

In [43]:
#columns function displays the columns in the dataset
print("\nThe column headings of the dataset:")
df.columns

The column headings of the dataset:

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [44]:
#Printing values
print("\n The values of the dataset: ")
df.values

 The values of the dataset:

array([['7590-VHVEG', 'Female', 0, ..., 29.85, '29.85', 'No'],
       ['5575-GNVDE', 'Male', 0, ..., 56.95, '1889.5', 'No'],
       ['3668-QPYBK', 'Male', 0, ..., 53.85, '108.15', 'Yes'],
       ...,
       ['4801-JZAZL', 'Female', 0, ..., 29.6, '346.45', 'No'],
       ['8361-LTMKD', 'Male', 1, ..., 74.4, '306.6', 'Yes'],
       ['3186-AJIEK', 'Male', 0, ..., 105.65, '6844.5', 'No']],
      dtype=object)

In [49]:
#dropping specific columns
print("\nDrop 'Gender' column: ")
print(df.drop(columns=['gender']))

Drop 'Gender' column:
      customerID  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     7590-VHVEG              0     Yes         No       1           No
1     5575-GNVDE              0      No         No      34          Yes
2     3668-QPYBK              0      No         No       2          Yes
3     7795-CFOCW              0      No         No      45           No
4     9237-HQITU              0      No         No       2          Yes
...          ...            ...     ...        ...     ...          ...
7038  6840-RESVB              0     Yes        Yes      24          Yes
7039  2234-XADUH              0     Yes        Yes      72          Yes
7040  4801-JZAZL              0     Yes        Yes      11           No
7041  8361-LTMKD              1     Yes         No       4          Yes
7042  3186-AJIEK              0      No         No      66          Yes

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes
1                   No             DSL            Yes           No
2                   No             DSL            Yes          Yes
3     No phone service             DSL            Yes           No
4                   No     Fiber optic             No           No
...                ...             ...            ...          ...
7038               Yes             DSL            Yes           No
7039               Yes     Fiber optic             No          Yes
7040  No phone service             DSL            Yes           No
7041               Yes     Fiber optic             No           No
7042                No     Fiber optic            Yes           No

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0                 Yes           Electronic check           29.85        29.85
1                  No               Mailed check           56.95       1889.5
2                 Yes               Mailed check           53.85       108.15
3                  No  Bank transfer (automatic)           42.30      1840.75
4                 Yes           Electronic check           70.70       151.65
...               ...                        ...             ...          ...
7038              Yes               Mailed check           84.80       1990.5
7039              Yes    Credit card (automatic)          103.20       7362.9
7040              Yes           Electronic check           29.60       346.45
7041              Yes               Mailed check           74.40        306.6
7042              Yes  Bank transfer (automatic)          105.65       6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 20 columns]

In [50]:
df.values

array([['7590-VHVEG', 'Female', 0, ..., 29.85, '29.85', 'No'],
       ['5575-GNVDE', 'Male', 0, ..., 56.95, '1889.5', 'No'],
       ['3668-QPYBK', 'Male', 0, ..., 53.85, '108.15', 'Yes'],
       ...,
       ['4801-JZAZL', 'Female', 0, ..., 29.6, '346.45', 'No'],
       ['8361-LTMKD', 'Male', 1, ..., 74.4, '306.6', 'Yes'],
       ['3186-AJIEK', 'Male', 0, ..., 105.65, '6844.5', 'No']],
      dtype=object)

In [51]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [52]:
#removing duplicate values
print("\nDrop duplicates: ")
print(df.drop_duplicates())

Drop duplicates:
      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95        1889.5
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 21 columns]

In [53]:
#checking null values
# fillna()
print("\nFill missing values with 0:")
print(df.fillna(0))

Fill missing values with 0:
      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95        1889.5
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 21 columns]

In [54]:
#checking for missing values and non-missing values
print("\nCheck formissing values: ")
print(df.isnull())
print("\nCheck for non-missing values: ")
print(df.notnull())

Check formissing values:
      customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0          False   False          False    False       False   False
1          False   False          False    False       False   False
2          False   False          False    False       False   False
3          False   False          False    False       False   False
4          False   False          False    False       False   False
...          ...     ...            ...      ...         ...     ...
7038       False   False          False    False       False   False
7039       False   False          False    False       False   False
7040       False   False          False    False       False   False
7041       False   False          False    False       False   False
7042       False   False          False    False       False   False

      PhoneService  MultipleLines  InternetService  OnlineSecurity  ...  \
0            False          False            False           False  ...
1            False          False            False           False  ...
2            False          False            False           False  ...
3            False          False            False           False  ...
4            False          False            False           False  ...
...            ...            ...              ...             ...  ...
7038         False          False            False           False  ...
7039         False          False            False           False  ...
7040         False          False            False           False  ...
7041         False          False            False           False  ...
7042         False          False            False           False  ...

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                False        False        False            False     False
1                False        False        False            False     False
2                False        False        False            False     False
3                False        False        False            False     False
4                False        False        False            False     False
...                ...          ...          ...              ...       ...
7038             False        False        False            False     False
7039             False        False        False            False     False
7040             False        False        False            False     False
7041             False        False        False            False     False
7042             False        False        False            False     False

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn
0                False          False           False         False  False
1                False          False           False         False  False
2                False          False           False         False  False
3                False          False           False         False  False
4                False          False           False         False  False
...                ...            ...             ...           ...    ...
7038             False          False           False         False  False
7039             False          False           False         False  False
7040             False          False           False         False  False
7041             False          False           False         False  False
7042             False          False           False         False  False

[7043 rows x 21 columns]

Check for non-missing values:
      customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0           True    True           True     True        True    True
1           True    True           True     True        True    True
2           True    True           True     True        True    True
3           True    True           True     True        True    True
4           True    True           True     True        True    True
...          ...     ...            ...      ...         ...     ...
7038        True    True           True     True        True    True
7039        True    True           True     True        True    True
7040        True    True           True     True        True    True
7041        True    True           True     True        True    True
7042        True    True           True     True        True    True

      PhoneService  MultipleLines  InternetService  OnlineSecurity  ...  \
0             True           True             True            True  ...
1             True           True             True            True  ...
2             True           True             True            True  ...
3             True           True             True            True  ...
4             True           True             True            True  ...
...            ...            ...              ...             ...  ...
7038          True           True             True            True  ...
7039          True           True             True            True  ...
7040          True           True             True            True  ...
7041          True           True             True            True  ...
7042          True           True             True            True  ...

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 True         True         True             True      True
1                 True         True         True             True      True
2                 True         True         True             True      True
3                 True         True         True             True      True
4                 True         True         True             True      True
...                ...          ...          ...              ...       ...
7038              True         True         True             True      True
7039              True         True         True             True      True
7040              True         True         True             True      True
7041              True         True         True             True      True
7042              True         True         True             True      True

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn
0                 True           True            True          True   True
1                 True           True            True          True   True
2                 True           True            True          True   True
3                 True           True            True          True   True
4                 True           True            True          True   True
...                ...            ...             ...           ...    ...
7038              True           True            True          True   True
7039              True           True            True          True   True
7040              True           True            True          True   True
7041              True           True            True          True   True
7042              True           True            True          True   True

[7043 rows x 21 columns]

In [55]:
#Getting summary statistics of a specific column
#mean() / median() / sum() / min() / max()
print("\nSummary statistics of tenure: ")
print("Mean :", df['tenure'].mean())
print("Median :", df['tenure'].median())
print("Total :", df['tenure'].sum())
print("Minimum :", df['tenure'].min())
print("Maximum :", df['tenure'].max())

Summary statistics of tenure:
Mean : 32.37114865824223
Median : 29.0
Total : 227990
Minimum : 0
Maximum : 72

DATAFRAME INDEXING OPERATIONS

DATAFRAME INDEXING

In [59]:
# Selecting Columns
print("Selecting Columns:")
print(df['customerID']) # using square brackets
print(df.tenure) # Using dot notation

Selecting Columns:
0       7590-VHVEG
1       5575-GNVDE
2       3668-QPYBK
3       7795-CFOCW
4       9237-HQITU
           ...
7038    6840-RESVB
7039    2234-XADUH
7040    4801-JZAZL
7041    8361-LTMKD
7042    3186-AJIEK
Name: customerID, Length: 7043, dtype: object
0        1
1       34
2        2
3       45
4        2
        ..
7038    24
7039    72
7040    11
7041     4
7042    66
Name: tenure, Length: 7043, dtype: int64

In [60]:
#LOCATION
#selecting rows
print("\nSelecting Rows: ")
print("Using .loc[]: ")
print(df.loc[1]) #label-based indexing
print("Using .iloc[]: ")
print(df.iloc[2]) #Integer-based indexing
print("Using boolean indexing:")
print(df[df['tenure'] > 30]) #booean indexing

Selecting Rows:
Using .loc[]:
customerID            5575-GNVDE
gender                      Male
SeniorCitizen                  0
Partner                       No
Dependents                    No
tenure                        34
PhoneService                 Yes
MultipleLines                 No
InternetService              DSL
OnlineSecurity               Yes
OnlineBackup                  No
DeviceProtection             Yes
TechSupport                   No
StreamingTV                   No
StreamingMovies               No
Contract                One year
PaperlessBilling              No
PaymentMethod       Mailed check
MonthlyCharges             56.95
TotalCharges              1889.5
Churn                         No
Name: 1, dtype: object
Using .iloc[]:
customerID              3668-QPYBK
gender                        Male
SeniorCitizen                    0
Partner                         No
Dependents                      No
tenure                           2
PhoneService                   Yes
MultipleLines                   No
InternetService                DSL
OnlineSecurity                 Yes
OnlineBackup                   Yes
DeviceProtection                No
TechSupport                     No
StreamingTV                     No
StreamingMovies                 No
Contract            Month-to-month
PaperlessBilling               Yes
PaymentMethod         Mailed check
MonthlyCharges               53.85
TotalCharges                108.15
Churn                          Yes
Name: 2, dtype: object
Using boolean indexing:
      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
1     5575-GNVDE    Male              0      No         No      34
3     7795-CFOCW    Male              0      No         No      45
9     6388-TABGU    Male              0      No        Yes      62
12    8091-TTVAX    Male              0     Yes         No      58
13    0280-XJGEX    Male              0      No         No      49
...          ...     ...            ...     ...        ...     ...
7033  9767-FFLEM    Male              0      No         No      38
7034  0639-TSIQW  Female              0      No         No      67
7037  2569-WGERO  Female              0      No         No      72
7039  2234-XADUH  Female              0     Yes        Yes      72
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
1             Yes                No             DSL                  Yes  ...
3              No  No phone service             DSL                  Yes  ...
9             Yes                No             DSL                  Yes  ...
12            Yes               Yes     Fiber optic                   No  ...
13            Yes               Yes     Fiber optic                   No  ...
...           ...               ...             ...                  ...  ...
7033          Yes                No     Fiber optic                   No  ...
7034          Yes               Yes     Fiber optic                  Yes  ...
7037          Yes                No              No  No internet service  ...
7039          Yes               Yes     Fiber optic                   No  ...
7042          Yes                No     Fiber optic                  Yes  ...

         DeviceProtection          TechSupport          StreamingTV  \
1                     Yes                   No                   No
3                     Yes                  Yes                   No
9                      No                   No                   No
12                    Yes                   No                  Yes
13                    Yes                   No                  Yes
...                   ...                  ...                  ...
7033                   No                   No                   No
7034                  Yes                   No                  Yes
7037  No internet service  No internet service  No internet service
7039                  Yes                   No                  Yes
7042                  Yes                  Yes                  Yes

          StreamingMovies        Contract PaperlessBilling  \
1                      No        One year               No
3                      No        One year               No
9                      No        One year               No
12                    Yes        One year               No
13                    Yes  Month-to-month              Yes
...                   ...             ...              ...
7033                   No  Month-to-month              Yes
7034                   No  Month-to-month              Yes
7037  No internet service        Two year              Yes
7039                  Yes        One year              Yes
7042                  Yes        Two year              Yes

                  PaymentMethod MonthlyCharges  TotalCharges Churn
1                  Mailed check          56.95        1889.5    No
3     Bank transfer (automatic)          42.30       1840.75    No
9     Bank transfer (automatic)          56.15       3487.95    No
12      Credit card (automatic)         100.35        5681.1    No
13    Bank transfer (automatic)         103.70        5036.3   Yes
...                         ...            ...           ...   ...
7033    Credit card (automatic)          69.50       2625.25    No
7034    Credit card (automatic)         102.95       6886.25   Yes
7037  Bank transfer (automatic)          21.15        1419.4    No
7039    Credit card (automatic)         103.20        7362.9    No
7042  Bank transfer (automatic)         105.65        6844.5    No

[3402 rows x 21 columns]

In [61]:
#conditional selection
print("\conditional selection: ")
print(df[df['gender'] == 'Male']) # selecting rows based on condition

\conditional selection:
      customerID gender  SeniorCitizen Partner Dependents  tenure  \
1     5575-GNVDE   Male              0      No         No      34
2     3668-QPYBK   Male              0      No         No       2
3     7795-CFOCW   Male              0      No         No      45
6     1452-KIOVK   Male              0      No        Yes      22
9     6388-TABGU   Male              0      No        Yes      62
...          ...    ...            ...     ...        ...     ...
7033  9767-FFLEM   Male              0      No         No      38
7035  8456-QDAVC   Male              0      No         No      19
7038  6840-RESVB   Male              0     Yes        Yes      24
7041  8361-LTMKD   Male              1     Yes         No       4
7042  3186-AJIEK   Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
6             Yes               Yes     Fiber optic             No  ...
9             Yes                No             DSL            Yes  ...
...           ...               ...             ...            ...  ...
7033          Yes                No     Fiber optic             No  ...
7035          Yes                No     Fiber optic             No  ...
7038          Yes               Yes             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
6                  No          No         Yes              No  Month-to-month
9                  No          No          No              No        One year
...               ...         ...         ...             ...             ...
7033               No          No          No              No  Month-to-month
7035               No          No         Yes              No  Month-to-month
7038              Yes         Yes         Yes             Yes        One year
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
1                  No               Mailed check          56.95        1889.5
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
6                 Yes    Credit card (automatic)          89.10        1949.4
9                  No  Bank transfer (automatic)          56.15       3487.95
...               ...                        ...            ...           ...
7033              Yes    Credit card (automatic)          69.50       2625.25
7035              Yes  Bank transfer (automatic)          78.70        1495.1
7038              Yes               Mailed check          84.80        1990.5
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
1       No
2      Yes
3       No
6       No
9       No
...    ...
7033    No
7035    No
7038    No
7041   Yes
7042    No

[3555 rows x 21 columns]

<>:2: SyntaxWarning: invalid escape sequence '\c'
<>:2: SyntaxWarning: invalid escape sequence '\c'
C:\Users\j\AppData\Local\Temp\ipykernel_13644\4174451948.py:2: SyntaxWarning: invalid escape sequence '\c'
  print("\conditional selection: ")

In [62]:
#setting index
print("\nSeting Index: ")
df_indexed = df.set_index('customerID')
print(df_indexed)

Seting Index:
            gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
customerID
7590-VHVEG  Female              0     Yes         No       1           No
5575-GNVDE    Male              0      No         No      34          Yes
3668-QPYBK    Male              0      No         No       2          Yes
7795-CFOCW    Male              0      No         No      45           No
9237-HQITU  Female              0      No         No       2          Yes
...            ...            ...     ...        ...     ...          ...
6840-RESVB    Male              0     Yes        Yes      24          Yes
2234-XADUH  Female              0     Yes        Yes      72          Yes
4801-JZAZL  Female              0     Yes        Yes      11           No
8361-LTMKD    Male              1     Yes         No       4          Yes
3186-AJIEK    Male              0      No         No      66          Yes

               MultipleLines InternetService OnlineSecurity OnlineBackup  \
customerID
7590-VHVEG  No phone service             DSL             No          Yes
5575-GNVDE                No             DSL            Yes           No
3668-QPYBK                No             DSL            Yes          Yes
7795-CFOCW  No phone service             DSL            Yes           No
9237-HQITU                No     Fiber optic             No           No
...                      ...             ...            ...          ...
6840-RESVB               Yes             DSL            Yes           No
2234-XADUH               Yes     Fiber optic             No          Yes
4801-JZAZL  No phone service             DSL            Yes           No
8361-LTMKD               Yes     Fiber optic             No           No
3186-AJIEK                No     Fiber optic            Yes           No

           DeviceProtection TechSupport StreamingTV StreamingMovies  \
customerID
7590-VHVEG               No          No          No              No
5575-GNVDE              Yes          No          No              No
3668-QPYBK               No          No          No              No
7795-CFOCW              Yes         Yes          No              No
9237-HQITU               No          No          No              No
...                     ...         ...         ...             ...
6840-RESVB              Yes         Yes         Yes             Yes
2234-XADUH              Yes          No         Yes             Yes
4801-JZAZL               No          No          No              No
8361-LTMKD               No          No          No              No
3186-AJIEK              Yes         Yes         Yes             Yes

                  Contract PaperlessBilling              PaymentMethod  \
customerID
7590-VHVEG  Month-to-month              Yes           Electronic check
5575-GNVDE        One year               No               Mailed check
3668-QPYBK  Month-to-month              Yes               Mailed check
7795-CFOCW        One year               No  Bank transfer (automatic)
9237-HQITU  Month-to-month              Yes           Electronic check
...                    ...              ...                        ...
6840-RESVB        One year              Yes               Mailed check
2234-XADUH        One year              Yes    Credit card (automatic)
4801-JZAZL  Month-to-month              Yes           Electronic check
8361-LTMKD  Month-to-month              Yes               Mailed check
3186-AJIEK        Two year              Yes  Bank transfer (automatic)

            MonthlyCharges TotalCharges Churn
customerID
7590-VHVEG           29.85        29.85    No
5575-GNVDE           56.95       1889.5    No
3668-QPYBK           53.85       108.15   Yes
7795-CFOCW           42.30      1840.75    No
9237-HQITU           70.70       151.65   Yes
...                    ...          ...   ...
6840-RESVB           84.80       1990.5    No
2234-XADUH          103.20       7362.9    No
4801-JZAZL           29.60       346.45    No
8361-LTMKD           74.40        306.6   Yes
3186-AJIEK          105.65       6844.5    No

[7043 rows x 20 columns]